### ISSUE TITLE
Docker image for arm v8 Raspberry Pi 

### ISSUE THREAD

**Issue by Sarin-jacob** [cioraneanu/firefly-pico#10]

**Comment by Call-Me-G-Now** [comment]
> +1

add a :+1: reaction on the original post instead of +1. Issues can be sorted on reactions

**Comment by Call-Me-G-Now** [comment]
if you guys follow the manual installation steps and add that to a dockerfile you can build your own image fairly easy.

**Comment by cioraneanu** [comment]
> Currently, the image cannot be built on ARM server because the [base Docker image](https://hub.docker.com/r/stsdockerhub/php) doesn't have an ARM version. Can a more popular Laravel base image be used to solve this?
> 
> To support ARM involves 2 tasks:
> 
> * Change Docker build to support ARM architecture.
> * Update Github Actions to build for multiple platforms.

Of course we can switch to a different base image 👍

**Comment by GDXbsv** [comment]
Does anybody have a working docker file for arm64 build?

**Comment by Call-Me-G-Now** [comment]
@GDXbsv @orguetta @Sarin-jacob 

I've put something together but can't test it.
Build looks fine, image size is rather large.
There's a `v7` and `v8` img. I'll look into arm64 as well.

`docker pull ghcr.io/call-me-g-now/firefly-pico:arm`

Please report back with your arch (`v7` or `v8`) if something doesn't work

**Comment by Call-Me-G-Now** [comment]
'arm64' added as well

`docker pull ghcr.io/call-me-g-now/firefly-pico:arm`

**Comment by Call-Me-G-Now** [comment]
@nghduc97

**Comment by geniusshiun** [comment]
I build a small apline arm version.
Try docker pull hsun666/firefly-pico-arm:v1.1.1.

**Comment by Call-Me-G-Now** [comment]
> I build a small apline arm version. Try docker pull hsun666/firefly-pico-arm:v1.1.1

wow, 110mb! that's pretty sweet. Can you share the `Dockerfile` pls? Does that include creating the `tar.gz` you use? If not, please share how you create the `tar.gz`.

**Comment by MnAppsNet** [comment]
Hello!
I have build a Dockerfile that uses the official alpine docker image as a base so you can build it for whatever platform you want.
https://github.com/MnAppsNet/firefly-pico-dockerfile
I have also build an image for amd64 and arm64:
https://hub.docker.com/r/mnapps/firefly-pico
I hope this helps :)

**Comment by cioraneanu** [comment]
Give the `:dev` docker image a try. Hopefully everything is ok :)

**Comment by Call-Me-G-Now** [comment]
LGTM!
