### ISSUE TITLE
Savings transactions cell is not clickable

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#102]
All other similar cells on the dashboard are clickable and lead to corresponding lists of transations but not this one. Is this expected?

**Comment by cioraneanu** [comment]
I wanted to implement it but it requires more work so I postponed for a later date. The savings transactions are related to several accounts and thus requires rewriting the filtering mechanism to support multiple values.

**Comment by fate8383** [comment]
I was losing my mind with that as well :) not clickable indeed. I was doing my math to guess where it comes from as it calculates some total amount and some percentage which I liked...not that I was deliberately saving anything but I like it to give me the idea :) looking forward to see those transactions list...mystery as it is now :) Great app all in all, well done.

**Comment by cioraneanu** [comment]
Thanks man! Will get to this one soon 😁

**Comment by cioraneanu** [comment]
Reworked the filtering mechanism. Give the `dev` docker tag a try, the savings cell should now be clickable 😇
