### ISSUE TITLE
[Suggestion] Color-code budgets

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#106]
Currently when budget is exceeded it's shown with a full green circle around it. Maybe we could change color to red in such cases to more clearly indicate them?
Also, potentially use yellow for "almost spent" budgets?

**Comment by cioraneanu** [comment]
Sounds like a great idea 👍

**Comment by cioraneanu** [comment]
Added it in the latest `dev` build. 
[BudgetIcon.vue](https://github.com/cioraneanu/firefly-pico/blob/dev/front/components/budget/budget-icon.vue). 
The colors/UI can probably be tweaked more down the line. 😁
