### ISSUE TITLE
Error when saving changes to account

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#109]
No matter what I change, save fails with the following error:
```
The opening balance date field is required when opening balance is present.
```
I suspect, this field was added recently and existing accounts don't have it - although they do have `opening_balance`, which causes this error.

Also note that there doesn't seem to be a way to change this field without adjusting balance.

**Comment by cioraneanu** [comment]
Fixed in #e728e48. Couldn't reproduce at first because it only applied for accounts created without an opening balance date.
