### ISSUE TITLE
Tags cant have uppercase letters

### ISSUE THREAD

**Issue by iLuckyW** [cioraneanu/firefly-pico#11]
Whenever I create a tag with uppercase letters in its name, the get converted to lowercase letters when I save them.

**Comment by cioraneanu** [comment]
This was a volutary decision to keep things uniform. Also in Firefly when creating a withdrawal, tags searching is case sensitive so I wanted to avoid the scenario in which you forget how you actually typed it.

**Comment by iLuckyW** [comment]
I see, maybe then a hint in the app would be useful, or even a setting to make this behavior optional. For me, it feels not very clear, the way it is right now.

**Comment by cioraneanu** [comment]
Fair. I'll change the label or placeholder to hint it :)
