### ISSUE TITLE
Budgets don't take into account Firefly auto-budget behaviours

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#113]
Looks like they all assume fixed amount per month as opposed to all other options:
<img width="409" alt="Screenshot 2024-09-30 at 12 38 18" src="https://github.com/user-attachments/assets/ae5cacd9-4a37-40fa-a067-a088a2373ba9">
<img width="144" alt="Screenshot 2024-09-30 at 12 37 23" src="https://github.com/user-attachments/assets/614dacea-d506-47b0-8a11-b4afe63387f9">
Percent shows correctly but amount is wrong

**Comment by cioraneanu** [comment]
Hopefuly it's fixed via d0bd6a7 😇.  Released version 1.4.2.
