### ISSUE TITLE
[Bug] Lowercase the names when editing the categories or tags

### ISSUE THREAD

**Issue by lvitti** [cioraneanu/firefly-pico#115]
I have the categories and tags in uppercase or PascalCase, but when editing to add an icon, it's automatically change to lowercase and don't allow to write any uppercase characters

**Comment by cioraneanu** [comment]
Is this option turned on? `Settings -> Formatting -> Force tag name lowercase`

**Comment by cioraneanu** [comment]
Thanks man, really appreciate it!😇
