### ISSUE TITLE
Show Balance Amount for Each Transaction

### ISSUE THREAD

**Issue by e-labInnovations** [cioraneanu/firefly-pico#116]
It's difficult to cross-check account balances between Firefly Pico and my bank passbook due to the absence of a balance amount displayed with each transaction. I recently noticed a mismatch between my actual bank balance and Firefly Pico's balance, and it was challenging to recheck every transaction without this feature.

**Feature Request**: Please add the option to display the balance amount alongside each transaction. This would make it much easier for users to reconcile accounts and ensure the accuracy of the data. If this feature can't be implemented in Firefly Pico, I'll raise this request in the Firefly III repository.

Thank you!

**Comment by cioraneanu** [comment]
I don't think this data is available in Firefly so you can try your luck opening an issue there as well :)
