### ISSUE TITLE
A couple changes needed to use SQLite

### ISSUE THREAD

**Issue by ethyoo** [cioraneanu/firefly-pico#127]
I am attempting to run Firefly-Pico with a SQLite database.

I was only able to do so after cloning the repository and making the following changes:
* **In the Dockerfile**: Add `php82-pdo_sqlite` to the installed packages. Resolves `could not find driver (Connection: sqlite, SQL: PRAGMA foreign_keys = ON;)`
* **In docker-entrypoint.d/start.sh**: Add a conditional statement  (e.g., `if [[ "$DB_CONNECTION" == "sqlite" ]]` or `if [[ -z "$DB_HOST" ]]`) to skip the database connectivity test

Does that seem correct?

**Comment by cioraneanu** [comment]
Yes that sounds perfect 👍
