### ISSUE TITLE
Split payment gets wrong information

### ISSUE THREAD

**Issue by NDelfs** [cioraneanu/firefly-pico#131]
**Versions used:**  
Firefly III - 6.1.24 with Schema V1  
Pico - 1.42  

**Setup in firefly**
A split payment with total of 2 splits.   
Description is different on both splits and then one description for total split. Each split has its own tag, see example   
![image](https://github.com/user-attachments/assets/60a49614-08f1-4e73-a87c-35cc8c839c78)
**View in Pico**  
But when I look at this in pico I will only see information of one of the splits while seeing the total sum of the splits  
![image](https://github.com/user-attachments/assets/2b4e66e3-bc90-4221-a31d-aa02002fc0d6)  

**Expected view in Pico**  
See total and both splits, similar to in firefly.  
or  
See total, and if possible tags of both.

**Comment by cioraneanu** [comment]
Thank you for opening the issue.

Since I am advocating against split transactions([Notes](https://github.com/cioraneanu/firefly-pico?tab=readme-ov-file#-notes)) they were not given much attention. 😄 

Will change it to show all tags(maybe even all categories), remove the orange label with something more in sync with the UI, and make the form actualy be disabled/readonly.

**Comment by NDelfs** [comment]
Thank you for taking the time to look into it!
Your proposed changes would make me happy enough. If it shows tags and categories correctly while being read only, we can learn to edit at evening at the computer in firefly. 

How come you are against split transactions? I do agree that the firefly GUI is making it needlessly complicated when it comes to setting it up. I would have liked a more automatic way to split of parts of the sum instead of manually calculating and filling in everything again. Now it is rather much like creating 2 transactions.

**Comment by cioraneanu** [comment]
Maybe an unpopular opinion but some reasons :)

- they make the UI more clutered for both viewing and creating transactions. This also comes with more code maintenance.
- they have some [constraints](https://docs.firefly-iii.org/how-to/firefly-iii/finances/transactions/#constraints)
- knowing that 2 expenses were performed "together" in the same store is not that valuable to me. If I ever change my mind about that I think I would rather use transaction links 🤔 
- it's easier for new users to understand. For every situation you just create a single transaction.
- sometimes I mark my transasctions with the "todo tag" to come back later and make some edits. Showing a long form with N splits in which I must find the one to change would not be great.

Last and not least creating 3 separate transactions with the assistant is fast and gives granular control. Not sure if the assistant can work with splits 😇

**Comment by cioraneanu** [comment]
Updated the UI to show all tags and categories. Give the `dev` docker image a go :)

**Comment by NDelfs** [comment]
wow that was a fast update, I'm impressed. The tags and category is now right,  
Is it possible to also get the description for the transaction instead of first found split? As in the picture above, willys söt is a split. While the transaction description is not even shown.  

Regarding the discussion above about alternatives, you mention transaction links. I can find these in the documentation, but not where in the software. How to set that up? 
I do not need a super complicated system. In my mind right now I only want the full sum on transaction and tags for part costs. Like the example above with sweets.

**Comment by cioraneanu** [comment]
Latest `dev` tag now shows the group description. 😄 

I haven't looked into it "transaction links", I just remembered seeing them mentioned in the docs. 

For your scenario I would just create 2 separate transactions. In such situations I look at the receipt(later when I have some down time) sum up things by category and create 1 expense for each. You could even just create one big expense when you leave the store and later create the other smaller transactions + edit the initial one. Or use split transactions inside Firefly III if that is what you like. There is no wrong way just use whatever makes you happy 😇

**Comment by NDelfs** [comment]
Great jobb. Now the presentation is as expected assuming your notes have been read 😄
