### ISSUE TITLE
Filters with special character such as "&" are not working

### ISSUE THREAD

**Issue by tiltshiftfocus** [cioraneanu/firefly-pico#139]
I have a category on Firefly III named as "Food & Drink".

Apparently when pico picks up this as a filter, the "&" in URL is written as is which is causing it to become a new parameter and resulting in an invalid GET request.

It needs to be encoded to `%26`.

URL example: `http://<host>:6976/api/search/transactions?query=type:%22withdrawal%22%20category_is:%22Food%20&%20Drink%22%20date_after:%222024-12-01%22%20date_before:%222024-12-31%22&page=1&limit=50`

Corrected version: `http://<host>:6976/api/search/transactions?query=type:%22withdrawal%22%20category_is:%22Food%20%26%20Drink%22%20date_after:%222024-12-01%22%20date_before:%222024-12-31%22&page=1&limit=50`

Note on `Food%20&%20Drink` and `Food%20%26%20Drink`.

**Comment by cioraneanu** [comment]
Thanks for sharing. Should be working now. 
Version `1.5.1` is up.

**Comment by cioraneanu** [comment]
You're right. During the 1.6.0 filter reimplemenation this got broken. Fixed in fbb3c06e98a9efb24427169ebb19df52d09baec7
Released in the `dev` docker tag.
