### ISSUE TITLE
[Suggestion] Add a setting for decimal delimiter

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#14]
Currently it uses "x.xxx,xx" format which is confusing for people used to "x,xxx.xx", especially when numbers are rounded.

Also, not sure if it's worth rounding total income/expense numbers on "current month" view on home page. Currency numbers are somehow easier to consume with decimals but maybe it's just my personal preference.

**Comment by cioraneanu** [comment]
An option to configure number formatting sounds good 👍

**Comment by cioraneanu** [comment]
Fixed in #30
