### ISSUE TITLE
Error: timeout of 4000 ms exceed

### ISSUE THREAD

**Issue by victor10292** [cioraneanu/firefly-pico#141]
I do love the application.  It's handy and beautiful. But I want to report a potential enhancement or bug.

This error message shows in the following two scenarios:

- Visiting the application for the first time. Every time I open the web browser and enter the URL in the address bar, it will show up. But if I change to other page and come back again, it works fine.
- Visiting the Transaction tab without any filter applied. When I change to Transaction page from Dashboard page, this error will occur. I guess it is because the system is trying to retrieve all the entries in the database, and I have more than 6,000 transaction journal records. It takes too much time to load. In the filter setting page, there is no any filters. Then I tried to add some filters, e.g. the transaction date range. It is okay if the search results is less than 350 records, or the error will occur. 

Could you please take a look at the performance issue? Maybe it is caused by Firefly III API. If it is, you can talk with the owner of Firefly III to see how to improve it. Last time, I found it is extremely slow to import records into Firefly III via API, roughly 40 seconds for an entry. I raised a ticket to the owner to get it fixed in a few days. The performance is significantly improved. 2 entries can be inserted in one second.

**Comment by cioraneanu** [comment]
Hello and thank you 😁 

You can increase your timeout by setting the docker env variable `NUXT_PUBLIC_QUERY_TIMEOUT=8000`.
The "transactions list" page always brings data paginated (50 per request) so even if you don't have any filters it should perform decently. 

Can you share what DB are you using for Firefly and how long one request for /api/transactions take? (In Chrome -> Inspect -> Network, the request you see after performing a pull to refresh in the transactions list)

**Comment by victor10292** [comment]
I am not using Docker. The APP is deployed in my server. So I can't set the environment parameter as you said. I found a similar variable in `front/nuxt.config.tx`: `queryTimeout`. I changed it from 4000 to 8000, and restart PM2. But the issue persisted. The alert message is still 4000 ms exceeded. If the change took effect, I would expect the error message is 8000 ms exceeded. 

Here is the screenshot from Chrome debug tool. The connection is broken after 4 seconds.

![2024-12-25_18-38](https://github.com/user-attachments/assets/157e4776-2464-4bc6-9274-df4d344af1e7)

I'm using Sqlite in Firefly-iii.

**Comment by cioraneanu** [comment]
You could also try to update the timeout for the backend http client, similar to this one 0638e85, and see if that changes it. 😄

**Comment by victor10292** [comment]
I use the API to list the transactions from the terminal. It takes a long time to retrieve the first page. Probably there is something wrong with the API. I would like to share the same problem with the Firefly owner to see what he can do on it.

BTW, I tried to modify the code you mentioned above by setting the timeout parameter as 30 seconds. There is no error message in `laravel.log`. But the connection is still broken after 4 seconds. 

![2024-12-26_18-18](https://github.com/user-attachments/assets/0ef24459-5fef-472c-81c6-4221a9575e41)

**Comment by victor10292** [comment]
I did additional testing. 

- Call api of `api/v1/transactions?start=2017-01-01&end=2024-12-31`, it takes 13.63 seconds to load the data.
- Call api of `api/v1/transactions?start=2024-01-01&end=2024-12-31`, it takes 2.64 seconds to load the data.

Based on this information, we can conclude that the more data in the query result set, the slower it is, even the api always only returns the first page data. So, is it possible to set a default ranger to narrow the query result in order to improve the user experience.

**Comment by cioraneanu** [comment]
You can try to open an issue with Firefly and see if you can get your response times up.

In your example you filtered data for 7 years, in Pico the Dashboard only applies a month interval for fetching so it's already pretty narrow.

**Comment by victor10292** [comment]
Yes, I have already opened an issue in Firefly. He will improve it in the future release.

I mean to set a default date range when clicking Transaction tab for the first time.

**Comment by cioraneanu** [comment]
And what response time do you get for the response without any filters?

**Comment by victor10292** [comment]
There are over 6,000 records in the database. It takes 24 seconds or so to load the first page without any filters.

**Comment by cioraneanu** [comment]
Oh... that's a huge difference. I guess I can add a new setting for user defined preaplied filters for such scenarios.

I know that there are a lot of variables here but with my current postgres db, I have around 1.2k transactions and they load in 400-500ms; also both normal and filtered by date take about the same.

**Comment by cioraneanu** [comment]
Created a new page in Settings -> Transactions -> Default list filters. Try out the `dev` docker tag 😁

**Comment by victor10292** [comment]
Do appreciate your efforts to add this new feature promptly. I am not using docker. So I will play it around once the code is changed in the repository.

**Comment by cioraneanu** [comment]
The code is already in the repository, just checkout the `dev` branch.  😇

**Comment by victor10292** [comment]
I tried, and it is nice. However, can I suggest to make the settings dynamic rather than static in terms of transaction date condition? For instance, it can be this year, this quarter, this month, and this week etc. Then the users don't need change it frequently.
