### ISSUE TITLE
[Suggestion] Expand "Expenses this week"

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#16]
Currently it shows the last week only and there is no way to see any other days. This is somewhat useless if you regularly (i.e., weekly) import bank transactions because most of the time this data will be incomplete.

Proposal: allow swiping this widget to see data for previous weeks. Or just load more data - i.e., for last month and make the view scrollable so no new data fetching is needed.

**Comment by cioraneanu** [comment]
I've played with showing columns for a full month but didn't like the outcome. There are higher chances to get a day in which you have a large spending(ex monthly mortgage) and then all the other 30 days have almost empty bars. 

For showing a full month a data a calendar view or a calendar heatmap would be better choices.
