### ISSUE TITLE
[Suggestion] Allow hiding accounts on the main dashboard

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#17]
If you have lots of accounts you may not really care about all of them all the time.
You could save some screen real estate if you allow marking some accounts as "hidden by default" so you would need to tap "See more" to show them. All totals would still include hidden accounts so it's purely a visual/extras change.

**Comment by cioraneanu** [comment]
I have a similar task on my todo list but with the option to exclude from the total calculated value. 

Guess there could be 2 checkboxes in the account form.

**Comment by avee87** [comment]
Pretty sure stock Firefly already has "include in net worth" checkbox

**Comment by cioraneanu** [comment]
Yes Firefly has it, but I don't manage it in Pico nor use it in the dashboard. Yet...😅

**Comment by cioraneanu** [comment]
Wooops. It seems like we've worked on the same thing :) Sorry for not assigning it faster it to let you know it's in the works.

This is my working [branch](https://github.com/cioraneanu/firefly-pico/tree/add-options-to-hide-accounts-on-dashboard). Almost done still need to test it and tweak the UI a little.

**Comment by cioraneanu** [comment]
Implemented via #43.
