### ISSUE TITLE
[Bug] Pico lowercases things when writing to Firefly

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#18]
I assigned icons to some categories and noticed that they changed from TitleCase to lowercase in Firefly itself.
Even when explicitly changing it to TitleCase in Pico it saves as lowercase. And if I then change name in Firefly, Pico remembers the old name in transaction lists.

Also, there is a typo in success message, it says "Succes" :)

**Comment by avee87** [comment]
Looks like entered transations also get lowercased

**Comment by avee87** [comment]
Here's the code doing it: https://github.com/cioraneanu/firefly-pico/blob/main/front/transformers/CategoryTransformer.js#L27
And similar in other transformers.

**Comment by cioraneanu** [comment]
This is just my preference. Maybe make a config for all of them / only leave the transaction description it the original case for the reasons mentioned in #11 .

**Comment by avee87** [comment]
Regardless of your preferences, it's not a pleasant experience when software silenty overrides your inputs - especially when it happens to existing production data that's not explicitly being edited - such as in the case of adding an icon to category.

If you really want to enforce lowercase, you should at least force lowercase in inputs so users can see what's going to be saved.

**Comment by cioraneanu** [comment]
Sure, that sounds reasonable.

**Comment by cioraneanu** [comment]
Fixed in #30
