### ISSUE TITLE
[Bug] Cross-currency transfers show source currency and value when viewing from receiving account

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#20]
Let's say you have a USD -> EUR transfer from account A to account B.
When viewing account B (which is in EUR) this transaction will show USD value which is not very useful in that context.

Also, there is no "Foreign amount" field when creating/editing a transfer.

**Comment by cioraneanu** [comment]
Transfers with different currencies are not implemented yet. Will look into it soon.
