### ISSUE TITLE
[Bug] Favicon doesn't show

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#21]
Despite it being in code, actual page shows nothing - at least on Chrome
<img width="235" alt="Screenshot 2024-05-07 at 23 36 51" src="https://github.com/cioraneanu/firefly-pico/assets/6134677/97fac3af-4265-4226-b78e-c6e074bc67b5">

**Comment by Call-Me-G-Now** [comment]
I see the same. The query returns a `200` though, the response is just 0 bytes:

```
HTTP/2 200 
server: nginx/1.23.3
date: Wed, 08 May 2024 08:54:02 GMT
content-type: image/x-icon
content-length: 0
last-modified: Tue, 07 May 2024 11:03:02 GMT
etag: "663a0a66-0"
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
accept-ranges: bytes
strict-transport-security: max-age=31536000
X-Firefox-Spdy: h2
```
