### ISSUE TITLE
Home page displays Expense and Revenue accounts

### ISSUE THREAD

**Issue by Call-Me-G-Now** [cioraneanu/firefly-pico#3]
My pico home page displays all accounts, asset - expense - revenue.

In your screenshot i only see asset accounts, that's also what i would prefer.

I looked on the settings page but didn't recognize a setting for this.

How do i change this behavior?

**Comment by cioraneanu** [comment]
Try out 1.0.2. You should only see your asste accounts. 😁

**Comment by Call-Me-G-Now** [comment]
yep, works thanks! 

BUT.... it still shows archived accounts (accounts that are no longer in use).

**Comment by cioraneanu** [comment]
That scenario requires adding a new property to accounts. Something like `is_dashboard_visible`. Will look into it the coming days. 🙂

**Comment by Call-Me-G-Now** [comment]
the ff3 rest-api `api/v1/accounts/<id>` returns this for an account, perhaps the `active` attribute is already available in the data you receive?

```JSON
{
    "data": {
        "type": "accounts",
        "id": "82",
        "attributes": {
            "created_at": "2024-03-11T19:33:06+01:00",
            "updated_at": "2024-03-25T22:00:18+01:00",
            "active": false,

```

**Comment by Call-Me-G-Now** [comment]
`api/v1/accounts` doesn't even return the inactive account. 

How do get the inactive accounts? Seems like you query them individually?

**Comment by cioraneanu** [comment]
Just created an inactive account and `api/v1/accounts` returns it. 
I will filter them by the active attribute, like you said, for a fast fix.

Will look later at the option to exclude them from dashboard manually for better control :)

**Comment by cioraneanu** [comment]
Give 1.0.3 a try. The inactive accounts should be excluded now. 😃

**Comment by Call-Me-G-Now** [comment]
works like a charm :+1: 


ps, postive intended sidenote; be 'careful' with submitting a lot of different type of changes in one commit. I would've split https://github.com/cioraneanu/firefly-pico/commit/c330b8d2be93a9f301da12e4c16fe83c12737fa8 into a lot more than one. Like here https://github.com/cioraneanu/firefly-pico/commit/0b89dc24136823812dc1a37cc46bb3ae408d0c50 as well. The compose changes "should've" been a different commit.

all positive my friend :+1:
