### ISSUE TITLE
[Suggestion] Persist settings in database

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#31]
Currently they live in local storage which means they are not shared across devices.
As the number of settings grows it becomes increasingly easy for them to go out of sync. Also if you ever clear local data in your browser you lose everything.

I would argue that only connection settings should live in local storage and the rest should be persisted.

**Comment by cioraneanu** [comment]
Persisting in DB would indeed have benefits but those settings need to be associated with an user. For example me and my wife both share the same Firefly acount but she has her own settings (ex.`New transaction defaults`). Creating separate login accounts(registration, account managent etc) for both Firefly and Pico don't seem like a great choice.  

One possible solution would be to create "profiles" and anyone with a valid Personal Token can choose which one to use. Thoughts? 🤔

**Comment by avee87** [comment]
Profile per token sounds like a great solution!

**Comment by avee87** [comment]
I will take a stab at this if you don't mind.

**Comment by cioraneanu** [comment]
Go right ahead😁 

One suggestion: in the database create a single column of type jsonb to store all user preferences.

**Comment by utzelberlin** [comment]
I'm sorry but i cannot be satisfied with this solution. I handle the data of my browser as deleted by close him. That's for security reasons.

The Personal Token is not really manageable. To recognize a user, there is the username/password concept and every browser can handle it (e.g. through AutoFill if I wish). This is not possible with a Personal Token I have to set every time I want to use Pico and the benefits of Pico (Ex. quick recording of transactions) are lost before I could start.

I also can't see why adjustments to the Firefly database should be necessary. Only one Pico table is required that connects username/password with the Pico Account Settings including a Personal Token. Or the 2 fields username/password in the Account Settings Table to find the right assignment.

With this solution your wife, you self and also I and all other Users could use Pico without  limitations. A checkbox "remember login" on the top could even avoid logging in for users who don't want to use it. Isn't it like that?

I would really like to use Pico. But unfortunately it doesn't help me with the daily manual copying and pasting of the Personal Token. I would be very grateful for a solution.
