### ISSUE TITLE
Wrong version number on settings page

### ISSUE THREAD

**Issue by Call-Me-G-Now** [cioraneanu/firefly-pico#4]
The version displayed on the settings page seems incorrect.

I'm running the docker:latest image. 
Latest is `sha256:15bb67648725` [latest](https://hub.docker.com/layers/cioraneanu/firefly-pico/latest/images/sha256-15bb67648725c10f5532d2b6ba960fa27a080b8ef3203e368a1a7f316f56d826?context=explore)
 and v1.0.1 is identical `sha256:15bb67648725` [v1.0.1](https://hub.docker.com/layers/cioraneanu/firefly-pico/1.0.1/images/sha256-15bb67648725c10f5532d2b6ba960fa27a080b8ef3203e368a1a7f316f56d826?context=explore)

Version page shows version 1.0.0 and shows there's a newer version 1.0.1 available.

![Screenshot from 2024-05-06 21-06-33](https://github.com/cioraneanu/firefly-pico/assets/125204742/adbc5e2b-af4e-4b78-ac9c-d7edd0bb159d)

**Comment by cioraneanu** [comment]
The 'latest' tag gets overwritten at every new release. If you redeploy your docker-compose you'll be on version 1.0.1

**Comment by Call-Me-G-Now** [comment]
agreed. that's not the issue. I'm running V1.0.1 with the screenshot above.

**Comment by Call-Me-G-Now** [comment]
aah, found it. the version in package.json wasn't updated:
https://github.com/cioraneanu/firefly-pico/blob/0b25188ec8013630eaebe2ec75a940387a70d93b/front/package.json#L2

just confirmed that this is fixed in v1.0.2

**Comment by cioraneanu** [comment]
Thank you for pointing it out 👍
