### ISSUE TITLE
[Bug] Database migrations don't run when updating to a newer version

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#48]
I installed a dev version of the Docker image containing dashboard visible field on accounts and it wasn't present in the database.
It required manually running migration from inside container but it should really be automatic.

Logs:
```
/docker-entrypoint.d/ is not empty, will attempt to perform configuration
Looking for shell scripts in /docker-entrypoint.d/
Launching /docker-entrypoint.d/1-configure-php.sh
Configure php
Launching /docker-entrypoint.d/2-configure-php-opcache.sh
Configure php opcache
Launching /docker-entrypoint.d/3-configure-php-fpm.sh
Configure php-fpm
Launching /docker-entrypoint.d/4-configure-nginx.sh
Configure nginx
Launching /docker-entrypoint.d/5-configure-laravel-scheduler.sh
Configure laravel scheduler
Launching /docker-entrypoint.d/6-configure-laravel-horizon.sh
Configure laravel horizon
Launching /docker-entrypoint.d/10-configure-back.sh
/docker-entrypoint.sh: line 12: /docker-entrypoint.d/10-configure-back.sh: not found
```

Also, for some reason `10-configure-back.sh` is the only script that actually exists in the repo. Where are others?

**Comment by cioraneanu** [comment]
Looks like somehow the `10-configure-back.sh` file didn't get copied. I cannot reproduce this on my end so you'll have to investigate further.

The other entry points are part of the base docker image.

**Comment by avee87** [comment]
The file is there:
```
/var/www/html/front # ls -lh /docker-entrypoint.d/
total 28K    
-rwxr-xr-x    1 root     root         829 Jul 18  2022 1-configure-php.sh
-rwxr-xr-x    1 root     root         590 Jan  6 19:53 10-configure-back.sh
-rwxr-xr-x    1 root     root        1.5K Jan 15 07:36 2-configure-php-opcache.sh
-rwxr-xr-x    1 root     root         751 Jul 22  2022 3-configure-php-fpm.sh
-rwxr-xr-x    1 root     root         488 Jul 22  2022 4-configure-nginx.sh
-rwxr-xr-x    1 root     root         492 Sep 21  2022 5-configure-laravel-scheduler.sh
-rwxr-xr-x    1 root     root         348 Jul 22  2022 6-configure-laravel-horizon.sh
```
But for some reason when I try to run it manually from inside container it shows as not found:
```
/var/www/html/front # /docker-entrypoint.d/10-configure-back.sh
sh: /docker-entrypoint.d/10-configure-back.sh: not found
```

**Comment by avee87** [comment]
After googling a bit more, it looks like `CRLF` issue. All other files use `LF` but this one is `CRLF` which causes `sh` not to see it.

After running `dos2unix /docker-entrypoint.d/10-configure-back.sh` inside container this script works fine again.
Interestingly enough, this file in repo seems to be `LF`, not sure how it changed to `CRLF`. Did you use Windows to build the container?

**Comment by cioraneanu** [comment]
Interesting find.👍 Yes manual docker builds were performed from both Windows and MacOS. Will look more into it to make sure it doesn't happen again.
