### ISSUE TITLE
[Bug][DarkMode] Currently selected tab is invisible

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#54]
<img width="359" alt="Screenshot 2024-05-18 at 12 12 55" src="https://github.com/cioraneanu/firefly-pico/assets/6134677/441c3a25-12e5-4a1d-920d-efb30c932b8b">

I think we should make it highlighted. Blue maybe?

**Comment by Call-Me-G-Now** [comment]
it should be white-bold, just like it is on white (black-bold).

This is what it looks like on my end:
![image](https://github.com/cioraneanu/firefly-pico/assets/125204742/2b47d5a5-21fc-4594-814c-534305bb8aa9)

**Comment by cioraneanu** [comment]
Dark theme is currently in alpha. Will be tweaking it in the coming days. Please don't open issues about it until I'm done since there will be lots of changes and most issues will probably become irelevant. Will create a new  dissusion/issue for feedback when I'm done 😁
