### ISSUE TITLE
[DarkMode] Default icons are invisible

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#61]
Default icons for accounts and categories blend into the background in dark mode. Assigned icons look fine though.

This happens on Categories and Accounts pages in Extras section

![Screenshot 2024-05-21 at 11 04 07](https://github.com/cioraneanu/firefly-pico/assets/6134677/af95e88d-5612-46e2-a979-d5607a9f7507)

**Comment by cioraneanu** [comment]
Fixed in 487f619. Played with the accent colors a bit as well.
