### ISSUE TITLE
Request to add this docker to Unraid

### ISSUE THREAD

**Issue by iweputo** [cioraneanu/firefly-pico#68]
Hi,

Many users that use Firefly III use it through Unraid, would it be possible to add this docker to the community apps inside unraid? for a simple clean install using the template

thank you

**Comment by cioraneanu** [comment]
Hi! Of course you can 👍

**Comment by iweputo** [comment]
The thing is i dont know how to do it, could you do it? or could someone do it

**Comment by cioraneanu** [comment]
Well I am not using Unraid, so if it is something that is important to you, you can always investigate how to do it 😉

**Comment by Lanjelin** [comment]
[my-firefly-pico.txt](https://github.com/user-attachments/files/16247758/my-firefly-pico.txt)

Download the template using the terminal, storing it in user template directory.
`wget https://github.com/user-attachments/files/16247758/my-firefly-pico.txt -O /boot/config/plugins/dockerMan/templates-user/my-firefly-pico.xml`

Click 'Add Container' under the Docker window, then select the template in the dropdown list.  

It would require though, that you install and configure postgresql first, with matching settings.
