### ISSUE TITLE
Transactions page shows nothing

### ISSUE THREAD

**Issue by avee87** [cioraneanu/firefly-pico#7]
I'm trying to connect Pico to my (quite large) Firefly instance. Every time I go to Transactions page it shows empty state. There are also some 500s in logs:

```
<REDACTED> - - [07/May/2024:01:33:05 +0300] [4.013] [4.013] "GET /api/transactions?page=1&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
<REDACTED> - - [07/May/2024:01:33:05 +0300] [4.012] [4.012] "GET /api/transactions?page=2&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
<REDACTED> - - [07/May/2024:01:33:05 +0300] [4.011] [4.010] "GET /api/transactions?page=3&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
```

It happens both for the list of all transations and when navigating to a specific account from homepage - although some accounts seem to load fine...

On unrelated note, please provide a way to pass timezone to the container - currently all logs show GMT+3 timezone.

**Comment by Call-Me-G-Now** [comment]
> On unrelated note, please provide a way to pass timezone to the container - currently all logs show GMT+3 timezone.

just set `TZ` to whatever you like

**Comment by Call-Me-G-Now** [comment]
> I'm trying to connect Pico to my (quite large) Firefly instance. Every time I go to Transactions page it shows empty state. There are also some 500s in logs:
> 
> ```
> <REDACTED> - - [07/May/2024:01:33:05 +0300] [4.013] [4.013] "GET /api/transactions?page=1&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
> <REDACTED> - - [07/May/2024:01:33:05 +0300] [4.012] [4.012] "GET /api/transactions?page=2&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
> <REDACTED> - - [07/May/2024:01:33:05 +0300] [4.011] [4.010] "GET /api/transactions?page=3&limit=50 HTTP/1.1" 499 0 "http://<REDACTED>:6976/transactions/list" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36" "-"
> 127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
> 127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
> 127.0.0.1 -  07/May/2024:01:33:01 +0300 "GET /index.php" 500
> ```
> 
> It happens both for the list of all transations and when navigating to a specific account from homepage - although some accounts seem to load fine...

the `500` means nginx can't reach `node` on port 3000, all inside the container.
sounds like `node` inside the container is not running properly. Verify that you have `Listening on http://[::]:3000` in your logs and check there are no errors or warnings.

**Comment by avee87** [comment]
Is there any caching for transactions?

Looks like when I navigate there the first time it takes a bunch of time and resources, I see 100% CPU and RAM usage, then it throws 500 and displays empty page. When I navigate there again there is instant 200 without CPU spikes and it still returns empty list.

**Comment by cioraneanu** [comment]
No there is no transaction caching. How many transactions do you currently have in your DB?

You can also try hitting the Firefly + Pico API directly maybe that helps narrow the issue.

`
curl --location 'https://firefly.example.com/api/v1/transactions?page=1&limit=50' --header 'authorization: Bearer exxxxx'
curl --location 'https://pico.example.com/api/transactions?page=1&limit=50' --header 'authorization: Bearer xxxxx'
`

**Comment by avee87** [comment]
I have lots of transactions :) Going back 10 years or so.
Will try hitting API directly later today.

**Comment by avee87** [comment]
Okay, I ran both requests via Postman and they both correctly returned transactions. Note that both requests took almost 10 seconds - could short timeout on the client be the issue?

**Comment by cioraneanu** [comment]
Woooow 🤯  What database are you using for Firefly?. There is currently a timeout of 4 seconds. Even if I make this value configurable I'm not sure it will be a pleasant experience to wait THAT long 😄 

Can you connect to the DB and run this query: `select count(*) from transaction_journals WHERE deleted_at is null`. Really curious about the size. 

I'm guessing it take forever for you to see reports / transaction lists inside the Firefly as well, right?

**Comment by avee87** [comment]
This query is instant:
```
MariaDB [firefly]> select count(*) from transaction_journals WHERE deleted_at is null;
+----------+
| count(*) |
+----------+
|    17726 |
+----------+
1 row in set (0.005 sec)
```
I imagine, Firefly transactions query does more than just querying the database - maybe it calculates account balances or something else that requires querying ALL transactions every time.

> I'm guessing it take forever for you to see reports / transaction lists inside the Firefly as well, right?

Yeah, it takes some time but I can live with it.

**Comment by Call-Me-G-Now** [comment]
I think the real thing to see here is that there should be some form of notification informing the user that something has timed out. 

maybe limit the pulls for transactions to x per query? say, limit 200 per transaction. Don't know how that would affect your internal workings. If you assume you have all data available than this would probably require a significant overhaul.

**Comment by cioraneanu** [comment]
Yup a timeout notification could be useful. 

Transaction GET requests are already paginated with a limit of 50.

**Comment by avee87** [comment]
From what I see, query running time doesn’t really depend on page size - i.e., fetching 10 transactions takes about the same time as fetching 50. That’s what makes me think that Firefly actually fetches all of them no matter what.

**Comment by cioraneanu** [comment]
> This query is instant:
> 
> ```
> MariaDB [firefly]> select count(*) from transaction_journals WHERE deleted_at is null;
> +----------+
> | count(*) |
> +----------+
> |    17726 |
> +----------+
> 1 row in set (0.005 sec)
> ```
> 
> I imagine, Firefly transactions query does more than just querying the database - maybe it calculates account balances or something else that requires querying ALL transactions every time.
> 
> > I'm guessing it take forever for you to see reports / transaction lists inside the Firefly as well, right?
> 
> Yeah, it takes some time but I can live with it.

The count is not that big. Firefly definetly does more work under the hood, but it's just way too much. I would suggest posting an issue of Firefly to raise some attention to it 👍

**Comment by avee87** [comment]
Oh well: https://github.com/firefly-iii/firefly-iii/issues/8873

**Comment by cioraneanu** [comment]
At least you tried  😃 Closing this since it's not a Pico issue. 

Added a sidequest on my personal todos to try and populate a fresh Firefly instance with 20k fake transactions and test if I get the same performance hit.

**Comment by avee87** [comment]
Where is timeout defined? Wonder if I could make it configurable via env...

**Comment by Call-Me-G-Now** [comment]
> Where is timeout defined? Wonder if I could make it configurable via env...

`CTRL+SHIFT+F` + `4000`

**Comment by avee87** [comment]
I also noticed that `/v1/accounts/{id}/transactions` endpoint is much faster - loads in less than 3 seconds compared to almost 10 seconds for transactions query. I wish we could use it in Pico instead...
