### ISSUE TITLE
Sync not retrieving Data

### ISSUE THREAD

**Issue by Duskadder** [cioraneanu/firefly-pico#70]
Everything seems to be running, Personal Token has been set yo, No errors, The Last sync date stamp appears on save in Pico but I'm not seeing any firefly data appearing such as accounts, tags or categories etc.

**Comment by cioraneanu** [comment]
On a Desktop open Chrome Dev Tools, hit save on the token screen and let me know what your console and network tabs show as errors.

**Comment by Duskadder** [comment]
![1](https://github.com/cioraneanu/firefly-pico/assets/62071393/0879ab45-9b0b-4bda-b396-2fda4a2660ce)
![2](https://github.com/cioraneanu/firefly-pico/assets/62071393/85e26f0d-ffe9-4c77-9698-971c0861d4c5)

**Comment by cioraneanu** [comment]
And in the network tab can you check if those requests have valid json responses?

**Comment by Duskadder** [comment]
![Screenshot 2024-06-04 at 16 52 44](https://github.com/cioraneanu/firefly-pico/assets/62071393/f83987de-02bf-4c70-8b39-3523d35449fd)

**Comment by cioraneanu** [comment]
Ok... you are not getting the expected backend JSONs from api endpoints but instead the frontend html.

Not sure where exactly things went south for you. Can you share your docker compose and if you use other reverse proxies in front of Pico? 


What you want to have: say your docker machine has an ip of 192.168.1.10 and exposes Pico on port 9000, accesing `http://192.168.1.10:9000/api/accounts` should give you a `{"message":"Unauthenticated"}`

**Comment by Duskadder** [comment]
OK, so revisiting the docker compose provided the answer. I had port 6976 on the docker host mapped to 6976 on Pico. Obviously that should have been mapped to port 80 on Pico. Made the change so 6976:80. Now everything works as expected. Thanks for taking the time to support.
