### ISSUE TITLE
Decimals in assistant

### ISSUE THREAD

**Issue by prophet6989** [cioraneanu/firefly-pico#75]
Hi!
I really like the idea and implementation of the assistant. But I can't use it to specify a non-integer value of the currency. If you write the decimal part separated by a dot or comma, it is ignored. And if you separate the decimal part with a space, then the sum is produced.
![Screenshot_8](https://github.com/cioraneanu/firefly-pico/assets/8154697/1a6a805d-f57f-43b6-a511-b3cbb4822b9c)
![Screenshot_9](https://github.com/cioraneanu/firefly-pico/assets/8154697/cf35dfcc-b535-429a-9bc8-2a971f5b3598)
![Screenshot_10](https://github.com/cioraneanu/firefly-pico/assets/8154697/cf74553a-6a44-4487-b999-eb451188ef79)

**Comment by cioraneanu** [comment]
Thanks for pointing it out. Give the `dev` docker tag a try and let me know if it's ok 😁

**Comment by prophet6989** [comment]
Decimals is working with `dev` docker tag) Thanks! When should this be expected in the `latest`?

**Comment by cioraneanu** [comment]
Version 1.2.0 will hit `latest` in about a week.
