### ISSUE TITLE
Error-Message when accessing home tab

### ISSUE THREAD

**Issue by iLuckyW** [cioraneanu/firefly-pico#83]
Whenever I open the home tab of firefly pico I get this error:

Error: file_put_contents(/var/www/html/storage/framework/cache/data/fa/6d/fa6db6627548516f25eddaeb5aa3fc7c78064954): Failed to open stream: No such file or directory

I tried restarting the container, but no luck, I still get the same message. So far I haven't found anything that isn't working, just this popup whenever I switch to that page. Any clues what could cause this?

**Comment by cioraneanu** [comment]
I'm getting the same error today but I'm away for the weekend and cannot investigate it until Monday. 

It looks like a filesystem/user permission issue. I guess if you run `php artisan cache:clear` it should go away? 🤔

**Comment by iLuckyW** [comment]
Thanks for the quick answer. Clearing the cache worked like a charm. The error is gone and everything back to normal. Not sure what cause the error in the end though.

**Comment by cioraneanu** [comment]
I've added the cache clear command as part of each deployment. 

Let me know if the problem reapers or if it was just a 1 time thing caused by the transition to the new Dockerfile.

**Comment by iLuckyW** [comment]
I think it was just a one time issue. It has been working great until then. Thanks for your help again
