### ISSUE TITLE
[Feature Request] FontAwesome Icons

### ISSUE THREAD

**Issue by Marco77577** [cioraneanu/firefly-pico#84]
For some topics, there are just not the right icons when creating tags. Could you connect the app to FontAwesome to make use of their extensive library?

https://fontawesome.com/icons

**Comment by cioraneanu** [comment]
The list of icons can be improved but mixing styles creates a horrible UI (I've tried it...)
This is disscused in #9. Handpicked icons + additional keywords offers a better result + discoverability.

**Comment by Marco77577** [comment]
Ah, I see. So you just added a subset of Microsoft's fluent icons? Why didn't you add all of them? Is it for storage space reasons/loading times when displaying the entire set?

**Comment by cioraneanu** [comment]
There are icons from several packs, i've mention the Fluent one because it is has a nice amount of icons which plays nicely with what we have so far. 

All icons are stored as SVGs so large collections will also impact size/performance.
