### ISSUE TITLE
[Bug] Save button hidden by bottom buttoms after scrolling.

### ISSUE THREAD

**Issue by captainrex493** [cioraneanu/firefly-pico#90]
On any menu with a save button, if the page is scrolled down, the save button goes behind the bottom buttons. Scrolling up does not cause the button to reappear. 
![thumbnail2](https://github.com/user-attachments/assets/305da5e0-5c7f-4632-9f7b-b8cfcb2ce83c)

**Comment by cioraneanu** [comment]
What OS and browser is that? Does the problem persist in other browsers?

**Comment by captainrex493** [comment]
The OS is Android 14 on a Pixel 7. The browser is Firefox v128.0.3. It also happens when using chrome. ![Screenshot_20240803-121503.png](https://github.com/user-attachments/assets/b4d23a25-ad44-44e8-bd65-d6f1caf67e4f)

**Comment by avee87** [comment]
I have an opposite issue on iOS sometimes - Save button stays in the middle of the screen obscuring other controls. Admittedly, it only seems to happen when keyboard is up.
![IMG_9384C51432FC-1](https://github.com/user-attachments/assets/383fcb6e-fafd-4886-a2d2-608788fd18ea)

**Comment by cioraneanu** [comment]
@captainrex493 I've managed to reproduce the issue on Firefox. Will look into it.

**Comment by cioraneanu** [comment]
@avee87 That's the default behaviour of iOS (it annoys me as well 😇 ). If you have the keyboard hidden, and tap an input in the bottom of the screen, the browser attempts to avoid having the input covered by CSS `position: fixed` elements so it moves them. 

Would love to have a solution for this as well :)

**Comment by cioraneanu** [comment]
@captainrex493 pushed a fix. Give the :dev docker tag a try and let me know if it's working as expected for you.

@avee87 handling the fixed button position while the keyboard is visible seems tricky :D i’ve played with the values provided by the Visual Viewport API but it’s not perfect; there seems to be some sort of offset that is missing.

**Comment by captainrex493** [comment]
The dev branch seems to work as expected.

**Comment by cioraneanu** [comment]
@avee87 1 million trial + errors later 😄 ... I think I've reached a decent solution to have the button react to the keyboard changes / input positions. Give the `dev` branch a shot. 😇
